FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install php -y
COPY  /websock .
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN composer install
CMD php app.php FOREGROUND